# The fitness function interface

import abc


class Fitness(metaclass=abc.ABCMeta):

    """
    The fitness object. Interface between ES and the users objective function.
    """
    @abc.abstractmethod
    def evaluate(self, params):
        """
        This function needs to be implemented to represent the objective function.

        Args:
            params(np.array): A flat numpy array representing a solution generated by ES.

        Returns:
            reward(float): A scalar value representing the evaluation of the objective function. ES is going to maximize
                           this value.

        """
        raise NotImplementedError

    @abc.abstractmethod
    def get_initial_solution(self):
        """
        This is usually a random solution. Its used as the starting point for training.

        Returns:
            sample(`np.array`)
        """
        raise NotImplementedError
